language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
    # not clear why pyarrow isn't using the wheel for cp38-macosx
    - CIBW_SKIP='cp27-* cp34-* cp38-* *-manylinux_i686'
    - CIBW_BEFORE_BUILD='pip install cmake'
    - CIBW_TEST_REQUIRES='nose'
    - CIBW_TEST_COMMAND='cd {project}; pip install -r test_requirements.txt; nosetests python/bamboo_tests'
    - CIBW_MANYLINUX1_X86_64_IMAGE=mvilim/bamboo_manylinux2014_x86_64
    - CIBW_ENVIRONMENT_MACOS='BAMBOO_USE_INSTALL=ON'
    - TWINE_USERNAME='mvilim'
    # TWINE_PASSWORD is stored in the travis project settings

script:
  - bash scripts/travis_build.sh

deploy:
  provider: script
  script: bash scripts/travis_deploy.sh
  skip_cleanup: true
  on:
    tags: true
